### ISSUE TITLE
Null safety and flutter2

### ISSUE THREAD

**Issue by ammaratef45** [Afonsocraposo/buttons_tabbar#14]
Need to upgrade to support null safety and flutter2

**Comment by Afonsocraposo** [comment]
Thank you for bringing my attention to that.
I'll try to do that over the weekend!

**Comment by Afonsocraposo** [comment]
Null safety and Flutter 2 is now supported: https://github.com/Afonsocraposo/buttons_tabbar/commit/94988fd0826ad5485b904cb23ead6d4fa29795df
Update your `pubspec.yaml` to version:
```yaml
dependencies:
  ...
  buttons_tabbar: ^1.2.0
```
