### ISSUE TITLE
Flutter 3.0.0 is detecting issue with the library 

### ISSUE THREAD

**Issue by RoyalCoder88** [afonsocraposo/buttons_tabbar#27]
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/buttons_tabbar-1.3.4/lib/buttons_tabbar.dart:180:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance

**Comment by gslender** [comment]
I've made the 1 line change in the code published in a fork I created, and added this to my pubspec.yaml

```
  # buttons_tabbar: ^1.3.4 # NOT V3 COMPATIBLE
  buttons_tabbar: #1.3.5 
    git:
      url: https://github.com/gslender/buttons_tabbar.git
```

When/if the package author gets around to updating, it is a simple change back in the pubspec
